"""Noisy QAOA simulator for the Quantum Portfolio Optimizer.

Runs the same portfolio QUBO as qaoa_simulator.py, but executes QAOA on
Qiskit Aer with a reproducible noise model. This gives us the second leg of
the benchmark pipeline: ideal simulator vs noisy simulator.
"""

from __future__ import annotations

import time

import numpy as np
from qiskit.primitives import BackendSamplerV2
from qiskit_aer import AerSimulator
from qiskit_aer.noise import NoiseModel, ReadoutError, depolarizing_error
from qiskit_algorithms.minimum_eigensolvers import QAOA
from qiskit_algorithms.optimizers import COBYLA
from qiskit_optimization.algorithms import MinimumEigenOptimizer

from qaoa_simulator import ASSETS, BUDGET, SEED, build_qubo


SHOTS = 2048
ONE_QUBIT_ERROR = 0.005
TWO_QUBIT_ERROR = 0.02
READOUT_ERROR = 0.02


def build_noise_model() -> NoiseModel:
    """Create a simple, reproducible NISQ-style noise model."""
    noise_model = NoiseModel()

    error_1q = depolarizing_error(ONE_QUBIT_ERROR, 1)
    error_2q = depolarizing_error(TWO_QUBIT_ERROR, 2)

    # Common basis gates generated by transpilation.
    noise_model.add_all_qubit_quantum_error(error_1q, ["x", "sx", "rz"])
    noise_model.add_all_qubit_quantum_error(error_2q, ["cx"])

    readout = ReadoutError(
        [
            [1.0 - READOUT_ERROR, READOUT_ERROR],
            [READOUT_ERROR, 1.0 - READOUT_ERROR],
        ]
    )
    noise_model.add_all_qubit_readout_error(readout)

    return noise_model


def run_noisy_qaoa() -> None:
    """Run QAOA with Aer noise and print benchmark-relevant metrics."""
    np.random.seed(SEED)

    qp = build_qubo()
    noise_model = build_noise_model()

    backend = AerSimulator(
        noise_model=noise_model,
        seed_simulator=SEED,
    )
    sampler = BackendSamplerV2(
        backend=backend,
        options={
            "default_shots": SHOTS,
            "seed_simulator": SEED,
        },
    )

    qaoa = QAOA(
        sampler=sampler,
        optimizer=COBYLA(maxiter=100),
        reps=1,
        initial_point=np.array([0.5, 0.5]),
    )
    optimizer = MinimumEigenOptimizer(qaoa)

    started = time.perf_counter()
    result = optimizer.solve(qp)
    runtime = time.perf_counter() - started

    selected_assets = [
        ASSETS[i] for i, value in enumerate(result.x) if int(round(value)) == 1
    ]

    print("=== Noisy QAOA Portfolio Simulator ===")
    print(f"Assets: {ASSETS}")
    print(f"Budget: {BUDGET}")
    print(f"Selected assets: {selected_assets}")
    print(f"Binary solution: {result.x.astype(int).tolist()}")
    print(f"Objective value: {result.fval:.6f}")
    print(f"Runtime: {runtime:.3f} s")
    print(f"Shots: {SHOTS}")
    print(f"QAOA reps: 1")
    print(f"1-qubit depolarizing error: {ONE_QUBIT_ERROR:.3%}")
    print(f"2-qubit depolarizing error: {TWO_QUBIT_ERROR:.3%}")
    print(f"Readout error: {READOUT_ERROR:.3%}")
    print(f"Seed: {SEED}")


if __name__ == "__main__":
    run_noisy_qaoa()
